compression-level = 9         # compression level for module zips. between 1 and 9
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1             # max number of concurrent building jobs
build-mindetach-module = false

# add 'enabled = false' for not patching a specific app or remove its entry
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
enabled = true
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                                 # space-seperated patches to exclude (multiline strings are not supported)
# space-seperated patches to include (non-excluded patches are included by default)
included-patches = "client-spoof copy-video-url custom-branding custom-video-buffering disable-auto-captions disable-shorts-on-startup downloads general-ads hdr-auto-brightness hide-breaking-news-shelf hide-crowdfunding-box hide-floating-microphone-button hide-watch-in-vr hide-watermark minimized-playback open-links-externally premium-heading remember-playback-rate remember-video-quality sponsorblock spoof-signature-verification video-ads"
# Excluded patches:
# always-autorepeat
# comments
# debugging
# disable-fullscreen-panels
# disable-player-popup-panels
# disable-zoom-haptics
# enable-wide-searchbar
# hide-album-cards
# hide-artist-card
# hide-autoplayer-button
# hide-captions-button
# hide-cast-button
# hide-create-button
# hide-email-address
# hide-endscreen-cards
# hide-floating-microphone-button
# hide-info-cards
# hide-my-mix
# hide-player-buttons
# hide-seekbar
# hide-shorts-button
# hide-timestamp
# hide-video-action-buttons
# microg-support
# old-quality-layout
# remove-player-button-background
# return-youtube-dislike
# seekbar-tapping
# spoof-app-version
# swipe-controls
# tablet-mini-player
# theme
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = true                                             # excludes all patches by default
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"

[Music-arm64]
enabled = false
build-mode = "both"
app-name = "Music"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrv-magisk"
arch = "arm64-v8a"

[Music-arm]
enabled = false
build-mode = "both"
app-name = "Music"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrv-arm-magisk"
arch = "arm-v7a"

[Twitter]
enabled = false
build-mode = "apk"
excluded-patches = "hide-views-stats"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"

[Reddit]
enabled = false
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Twitch]
enabled = true
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[TikTok]
enabled = false
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Spotify]
enabled = false
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
arch = "arm64-v8a"

[Backdrops]
enabled = false
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
arch = "arm64-v8a"

[Tasker]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
